version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://seattle_weather_user:hS1yirAgqJqyY6Kd6KMgwuKkTEhZInQn@dpg-cvmr6sp5pdvs73flesc0-a.oregon-postgres.render.com/seattle_weather
      - DB_SSL_MODE=require
    command: >
      sh -c "python -m src.app.database &&
      uvicorn src.app.main:app --host 0.0.0.0 --port 8000"